apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: church-cms-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: church-cms
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/bankolejohn/church-idea.git
    targetRevision: main
    path: helm/church-cms
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: church-cms-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m0s
